from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fondo = QtWidgets.QLabel(self.centralwidget)
        self.fondo.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.fondo.setText("")
        self.fondo.setPixmap(QtGui.QPixmap("img/Diseño casa TIC2.png"))
        self.fondo.setScaledContents(True)
        self.fondo.setAlignment(QtCore.Qt.AlignCenter)
        self.fondo.setObjectName("fondo")
        self.cuartoA = QtWidgets.QLabel(self.centralwidget)
        self.cuartoA.setGeometry(QtCore.QRect(90, 140, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cuartoA.setFont(font)
        self.cuartoA.setTextFormat(QtCore.Qt.RichText)
        self.cuartoA.setScaledContents(False)
        self.cuartoA.setAlignment(QtCore.Qt.AlignCenter)
        self.cuartoA.setObjectName("cuartoA")
        self.cuartoB = QtWidgets.QLabel(self.centralwidget)
        self.cuartoB.setGeometry(QtCore.QRect(460, 140, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cuartoB.setFont(font)
        self.cuartoB.setTextFormat(QtCore.Qt.RichText)
        self.cuartoB.setScaledContents(False)
        self.cuartoB.setAlignment(QtCore.Qt.AlignCenter)
        self.cuartoB.setObjectName("cuartoB")
        self.banoA = QtWidgets.QLabel(self.centralwidget)
        self.banoA.setGeometry(QtCore.QRect(90, 430, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.banoA.setFont(font)
        self.banoA.setTextFormat(QtCore.Qt.RichText)
        self.banoA.setScaledContents(False)
        self.banoA.setAlignment(QtCore.Qt.AlignCenter)
        self.banoA.setObjectName("banoA")
        self.banoB = QtWidgets.QLabel(self.centralwidget)
        self.banoB.setGeometry(QtCore.QRect(570, 470, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.banoB.setFont(font)
        self.banoB.setTextFormat(QtCore.Qt.RichText)
        self.banoB.setScaledContents(False)
        self.banoB.setAlignment(QtCore.Qt.AlignCenter)
        self.banoB.setObjectName("banoB")
        self.cocina = QtWidgets.QLabel(self.centralwidget)
        self.cocina.setGeometry(QtCore.QRect(1080, 80, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cocina.setFont(font)
        self.cocina.setTextFormat(QtCore.Qt.RichText)
        self.cocina.setScaledContents(False)
        self.cocina.setAlignment(QtCore.Qt.AlignCenter)
        self.cocina.setObjectName("cocina")
        self.living = QtWidgets.QLabel(self.centralwidget)
        self.living.setGeometry(QtCore.QRect(850, 530, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.living.setFont(font)
        self.living.setTextFormat(QtCore.Qt.RichText)
        self.living.setScaledContents(False)
        self.living.setAlignment(QtCore.Qt.AlignCenter)
        self.living.setObjectName("living")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cuartoA.setText(_translate("MainWindow", ""))
        self.cuartoB.setText(_translate("MainWindow", ""))
        self.banoA.setText(_translate("MainWindow", ""))
        self.banoB.setText(_translate("MainWindow", ""))
        self.cocina.setText(_translate("MainWindow", ""))
        self.living.setText(_translate("MainWindow", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
